//! Stub module auto-generated by `zig init`.
//! Kept so the default `zig build test` passes.

const std = @import("std");

pub fn add(a: i32, b: i32) i32 {
    return a + b;
}

test "basic add functionality" {
    try std.testing.expect(add(3, 7) == 10);
}
